### INTRODUCTION TO 'NUMPY':

In [1]:
import numpy as np

#### Review if 'LIST', ARRAY' and their manipulation:

In [2]:
my_int_list=[2,4,1,6,8,0,9,7,3]
print(my_int_list)

[2, 4, 1, 6, 8, 0, 9, 7, 3]


In [3]:
my_float_list=[2.7,4.0,5.5,6,8.9,1,9.123,7.1,10]
print(my_float_list)

[2.7, 4.0, 5.5, 6, 8.9, 1, 9.123, 7.1, 10]


In [4]:
len(my_int_list)

9

In [5]:
my_float_list.append(0.007)
print(my_float_list)

[2.7, 4.0, 5.5, 6, 8.9, 1, 9.123, 7.1, 10, 0.007]


In [6]:
np.sum(my_int_list)

40

In [7]:
np.sqrt(my_int_list)

array([1.41421356, 2.        , 1.        , 2.44948974, 2.82842712,
       0.        , 3.        , 2.64575131, 1.73205081])

In [8]:
np.sin(my_int_list)

array([ 0.90929743, -0.7568025 ,  0.84147098, -0.2794155 ,  0.98935825,
        0.        ,  0.41211849,  0.6569866 ,  0.14112001])

### 'ARRAY' IN NUMPY & ITS MANIPULATION

In [9]:
my_int_array=np.array(my_int_list)
print(my_int_array)

[2 4 1 6 8 0 9 7 3]


In [10]:
type(my_int_list)

list

In [11]:
type(my_int_array)

numpy.ndarray

In [12]:
my_int_array.dtype

dtype('int32')

In [13]:
print(my_int_array)

[2 4 1 6 8 0 9 7 3]


In [14]:
print(my_int_array.shape)

(9,)


In [15]:
print(np.sort(my_int_array))
print(-np.sort(-my_int_array))

[0 1 2 3 4 6 7 8 9]
[9 8 7 6 4 3 2 1 0]


In [16]:
my_int_array.size

9

In [17]:
my_float_list=[2.7,4.0,5.5,6,8.9,1,9.123,7.1,10]
print(my_float_list)

[2.7, 4.0, 5.5, 6, 8.9, 1, 9.123, 7.1, 10]


In [18]:
my_float_array=np.array(my_float_list)
print(my_float_array)

[ 2.7    4.     5.5    6.     8.9    1.     9.123  7.1   10.   ]


In [19]:
my_float_array.size

9

In [20]:
my_float_array.itemsize

8

In [21]:
my_float_array1=my_float_array[[0,1,2]],[[3,4,5]],[[6,7,8]]
print(my_float_array1)

(array([2.7, 4. , 5.5]), [[3, 4, 5]], [[6, 7, 8]])


In [22]:
type(my_float_array)

numpy.ndarray

In [23]:
print('my_float_array')

my_float_array


In [24]:
my_float_array.dtype

dtype('float64')

In [25]:
print(my_float_array)

[ 2.7    4.     5.5    6.     8.9    1.     9.123  7.1   10.   ]


In [26]:
print(my_float_array.shape)

(9,)


In [27]:
my_integer_arraya = np.arange(9)
print(my_integer_arraya)

[0 1 2 3 4 5 6 7 8]


### MATRIX IN NUMPY & ITS MANUPULATION

In [28]:
mat03=np.zeros((3,3))
print(mat03)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.matmul(A,B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [30]:
print(np.dot(A,B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [31]:
iden3=np.eye(3,3)
print(iden3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
np.ide(3)

AttributeError: module 'numpy' has no attribute 'ide'

In [33]:
ones3=np.ones((3,3))
ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
ran3=np.random.random((3,3))
print(ran3)

[[0.43205459 0.16181048 0.78084639]
 [0.89323608 0.1640895  0.35344412]
 [0.15388861 0.15979686 0.28998268]]


In [35]:
data = np.arange(8).reshape(4,2)
print(data)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [36]:
np.transpose(data)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [37]:
A1=([[1,3,5],[7,9,11],[13,15,17]])
display(A1)

[[1, 3, 5], [7, 9, 11], [13, 15, 17]]

In [38]:
A2 = np.arange(1,19,2).reshape(3,3) 
display(A2)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [39]:
A3=np.matrix('1,3,5;7,9,11;13,15,17') 
display(A3)

matrix([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]])

In [40]:
display(A1-A2)
display(A2-A3)
display(A3-A1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [41]:
display(np.trace(A1),np.trace(A2),np.trace(A3))

27

27

27

In [42]:
A = np.arange(0,9,1).reshape(3,3);
B = np.arange(1,10).reshape(3,3);
AB=np.dot(A,B);
BA=np.dot(B,A);
print(AB-BA)

[[ -6  -9 -12]
 [  3   0  -3]
 [ 12   9   6]]


In [43]:
A = np.arange(0,9).reshape(3,3)
V = np.arange(3).reshape(1,3)
V1=np.transpose(V)
print(A)
print(V1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]]


In [44]:
np.dot(A,V1)

array([[ 5],
       [14],
       [23]])

In [45]:
np.inner(V, V)

array([[5]])

In [46]:
np.dot(V, V1)

array([[5]])

In [47]:
np.random.rand(3,3)

array([[0.04314309, 0.51508701, 0.22162856],
       [0.8502512 , 0.98138472, 0.7975097 ],
       [0.61467989, 0.38915834, 0.46383265]])

In [48]:
A =np.array(np.arange(2,11).reshape(3,3))
print(A)
Aa=np.array(A)
print(Aa)
A-Aa

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#### Pauli Matrices & their Properies (To be dealt in separate file)

In [49]:
sx = np.matarray([[0, 1],[ 1, 0]])
sy = array([[0, -1j],[1j, 0]])
sz = array([[1, 0],[0, -1]])
I2 = array([[1, 0],[0, 1]])

AttributeError: module 'numpy' has no attribute 'matarray'

In [50]:
spin_up = array([[1],[0]])
spin_down = array([[0],[1]])

NameError: name 'array' is not defined

### USING LINEAR ALGBRA PACKAGE IN 'NUMPY':

In [51]:
A= np.arange(1,19,2).reshape(3,3) 
display(A)
np.linalg.inv(A)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

array([[-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14]])

In [52]:
A1=([[1,3,5],[7,9,11],[13,15,17]])
A2 = np.arange(1,19,2).reshape(3,3) 
A3=np.matrix('1,3,5;7,9,11;13,15,17')

In [53]:
invA1=np.linalg.inv(A1) 
invA2=np.linalg.inv(A2) 
invA3=np.linalg.inv(A3) 
print(invA1) 
print(invA2) 
print(invA3)

[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]
[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]
[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
 [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
 [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]


In [54]:
x = np.array([[1,2],[3,4]]) 
y=np.linalg.inv(x) 
print(y) 

[[-2.   1. ]
 [ 1.5 -0.5]]


In [55]:
A=[[1,1,1],[0,2,5],[2,5,-1]]
display(A)
invA = np.linalg.inv(A) 
print(A) 
print(invA) 
print(np.dot(A,invA))

[[1, 1, 1], [0, 2, 5], [2, 5, -1]]

[[1, 1, 1], [0, 2, 5], [2, 5, -1]]
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
[[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  5.55111512e-17  1.00000000e+00]]


In [56]:
x = np.array([[1,2],[3,4]]) 
invx = np.linalg.inv(x) 
print(x) 
print(invx) 
print( np.dot(x,invx))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [57]:
a = np.array([[1,1,1],[0,2,5],[2,5,-1]])
ainv = np.linalg.inv(a)
print(ainv)

[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]


In [58]:
mat3=np.matrix('1,2,3;7,5,6;7,8,9') 
print(mat3)
np.linalg.inv(mat3)

[[1 2 3]
 [7 5 6]
 [7 8 9]]


matrix([[-0.16666667,  0.33333333, -0.16666667],
        [-1.16666667, -0.66666667,  0.83333333],
        [ 1.16666667,  0.33333333, -0.5       ]])

In [59]:
np.trace(mat3)

15

In [60]:
np.linalg.det(mat3)

18.000000000000004

In [61]:
np.linalg.matrix_rank(mat3)

3

In [62]:
mat3=np.matrix('1,2,3;7,5,6;7,8,9') 
evalues, evectors = np.linalg.eig(mat3)
print(evalues)
print(evectors)

[16.51885049+0.j         -0.75942525+0.71619655j -0.75942525-0.71619655j]
[[ 0.22627225+0.j         -0.28163546+0.276909j   -0.28163546-0.276909j  ]
 [ 0.55460785+0.j          0.78267474+0.j          0.78267474-0.j        ]
 [ 0.80075652+0.j         -0.42271807-0.22963568j -0.42271807+0.22963568j]]


In [63]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# calculate eigendecomposition
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Solution of linear equation: $$A\cdot \vec{x}=\vec{b}$$

In [64]:
A = np.array([[1, 2.6, 3], [4, 5.0, 6], [7, .8, 9]])
b=np.array([1.5,2.1,3.7])
b.transpose()
b.dot(b.transpose())
x = np.linalg.solve(A, b)
print(x)
np.allclose(np.dot(A, x), b)

[-0.46515152 -0.15151515  0.78636364]


True

In [65]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)
np.allclose(np.dot(a, x), b)

[2. 3.]


True

### Eigen Value Decomposition (Similarity Transformation): $$A=PDP^{-1} \quad {\rm or} \quad D=P^{-1}AP $$

In [66]:
A = np.array([[1, 2.6, 3], [4, 5.0, 6], [7, .8, 9]])
(d,P)=np.linalg.eig(A)
D=np.diag(d)
print(d)
print(D)
print(P)

[13.01427117 -1.01427117  3.        ]
[[13.01427117  0.          0.        ]
 [ 0.         -1.01427117  0.        ]
 [ 0.          0.          3.        ]]
[[ 0.31322502  0.8182014  -0.32444284]
 [ 0.6643757   0.0286801  -0.81110711]
 [ 0.67859783 -0.57421592  0.48666426]]


In [67]:
M=np.dot(np.dot(P,D),np.linalg.inv(P))
print(M)

[[1.  2.6 3. ]
 [4.  5.  6. ]
 [7.  0.8 9. ]]


In [68]:
np.diag(np.dot(np.dot(np.linalg.inv(P),M),P))

array([13.01427117, -1.01427117,  3.        ])

### Singular Value Decomposition: $$(A=USV^T)$$

In [69]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [70]:
quit()